import sys
import re

DESCRIPTIONS = {
    "Merge Two Sorted Lists": "You are given the heads of two sorted linked lists list1 and list2.\\n\\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\\n\\nReturn the head of the merged linked list.\\n\\nExample 1:\\nInput: list1 = [1,2,4], list2 = [1,3,4]\\nOutput: [1,1,2,3,4,4]\\nExplanation: The first list has elements 1, 2, 4. The second list has elements 1, 3, 4. Splicing them in ascending order yields 1 -> 1 -> 2 -> 3 -> 4 -> 4.\\n\\nExample 2:\\nInput: list1 = [], list2 = []\\nOutput: []\\nExplanation: Both lists are empty, so the merged list is also empty.\\n\\nExample 3:\\nInput: list1 = [], list2 = [0]\\nOutput: [0]\\nExplanation: The first list is empty, so we just return the second list.",
    "Maximum Subarray": "Given an integer array nums, find the subarray with the largest sum, and return its sum.\\n\\nA subarray is a contiguous non-empty sequence of elements within an array.\\n\\nExample 1:\\nInput: nums = [-2,1,-3,4,-1,2,1,-5,4]\\nOutput: 6\\nExplanation: The subarray [4,-1,2,1] has the largest sum 6.\\n\\nExample 2:\\nInput: nums = [1]\\nOutput: 1\\nExplanation: The subarray [1] has the largest sum 1.\\n\\nExample 3:\\nInput: nums = [5,4,-1,7,8]\\nOutput: 23\\nExplanation: The subarray [5,4,-1,7,8] has the largest sum 5 + 4 + (-1) + 7 + 8 = 23.",
    "Container With Most Water": "You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).\\n\\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\\n\\nReturn the maximum amount of water a container can store.\\n\\nExample 1:\\nInput: height = [1,8,6,2,5,4,8,3,7]\\nOutput: 49\\nExplanation: The max area of water (blue section) the container can contain is 49.\\n\\nExample 2:\\nInput: height = [1,1]\\nOutput: 1\\nExplanation: The container formed by the lines at index 0 and 1 has height 1 and width 1, yielding an area of 1.\\n\\nExample 3:\\nInput: height = [4,3,2,1,4]\\nOutput: 16\\nExplanation: The lines at index 0 and 4 form a container of height 4 and width 4, yielding an area of 16.",
    "3Sum": "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.\\n\\nNotice that the solution set must not contain duplicate triplets.\\n\\nExample 1:\\nInput: nums = [-1,0,1,2,-1,-4]\\nOutput: [[-1,-1,2],[-1,0,1]]\\nExplanation: The distinct triplets are [-1,0,1] and [-1,-1,2].\\n\\nExample 2:\\nInput: nums = [0,1,1]\\nOutput: []\\nExplanation: The only possible triplet does not sum up to 0.\\n\\nExample 3:\\nInput: nums = [0,0,0]\\nOutput: [[0,0,0]]\\nExplanation: The only possible triplet sums up to 0.",
    "Longest Substring Without Repeating Characters": "Given a string s, find the length of the longest substring without repeating characters.\\n\\nExample 1:\\nInput: s = \"abcabcbb\"\\nOutput: 3\\nExplanation: The answer is \"abc\", with the length of 3.\\n\\nExample 2:\\nInput: s = \"bbbbb\"\\nOutput: 1\\nExplanation: The answer is \"b\", with the length of 1.\\n\\nExample 3:\\nInput: s = \"pwwkew\"\\nOutput: 3\\nExplanation: The answer is \"wke\", with the length of 3. Notice that the answer must be a substring, \"pwke\" is a subsequence and not a substring.",
    "Trapping Rain Water": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.\\n\\nExample 1:\\nInput: height = [0,1,0,2,1,0,1,3,2,1,2,1]\\nOutput: 6\\nExplanation: The elevation map is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water are being trapped.\\n\\nExample 2:\\nInput: height = [4,2,0,3,2,5]\\nOutput: 9\\nExplanation: The elevation map is represented by array [4,2,0,3,2,5]. In this case, 9 units of rain water are being trapped.\\n\\nExample 3:\\nInput: height = [1,0,1]\\nOutput: 1\\nExplanation: The elevation map is represented by array [1,0,1]. In this case, 1 unit of rain water is trapped between the two bars.",
    "N-Queens": "The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.\\n\\nGiven an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.\\n\\nExample 1:\\nInput: n = 4\\nOutput: [[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]\\nExplanation: There exist two distinct solutions to the 4-queens puzzle.\\n\\nExample 2:\\nInput: n = 1\\nOutput: [[\"Q\"]]\\nExplanation: There exists one distinct solution to the 1-queens puzzle.\\n\\nExample 3:\\nInput: n = 2\\nOutput: []\\nExplanation: There are no distinct solutions to the 2-queens puzzle.",
    "Binary Search": "Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.\\n\\nYou must write an algorithm with O(log n) runtime complexity.\\n\\nExample 1:\\nInput: nums = [-1,0,3,5,9,12], target = 9\\nOutput: 4\\nExplanation: 9 exists in nums and its index is 4.\\n\\nExample 2:\\nInput: nums = [-1,0,3,5,9,12], target = 2\\nOutput: -1\\nExplanation: 2 does not exist in nums so return -1.\\n\\nExample 3:\\nInput: nums = [5], target = 5\\nOutput: 0\\nExplanation: 5 exists in nums and its index is 0.",
    "Climbing Stairs": "You are climbing a staircase. It takes n steps to reach the top.\\n\\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?\\n\\nExample 1:\\nInput: n = 2\\nOutput: 2\\nExplanation: There are two ways to climb to the top:\\n1. 1 step + 1 step\\n2. 2 steps\\n\\nExample 2:\\nInput: n = 3\\nOutput: 3\\nExplanation: There are three ways to climb to the top:\\n1. 1 step + 1 step + 1 step\\n2. 1 step + 2 steps\\n3. 2 steps + 1 step\\n\\nExample 3:\\nInput: n = 4\\nOutput: 5\\nExplanation: There are five ways to climb to the top:\\n1. 1+1+1+1\\n2. 1+1+2\\n3. 1+2+1\\n4. 2+1+1\\n5. 2+2",
    "Valid Anagram": "Given two strings s and t, return true if t is an anagram of s, and false otherwise.\\n\\nAn Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.\\n\\nExample 1:\\nInput: s = \"anagram\", t = \"nagaram\"\\nOutput: true\\nExplanation: The string \"nagaram\" is an anagram of \"anagram\".\\n\\nExample 2:\\nInput: s = \"rat\", t = \"car\"\\nOutput: false\\nExplanation: The string \"car\" is not an anagram of \"rat\".\\n\\nExample 3:\\nInput: s = \"a\", t = \"ab\"\\nOutput: false\\nExplanation: The strings have different lengths, so they cannot be anagrams.",
    "Group Anagrams": "Given an array of strings strs, group the anagrams together. You can return the answer in any order.\\n\\nExample 1:\\nInput: strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]\\nOutput: [[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]\\nExplanation: There is no string in strs that can be an anagram of \"bat\". The strings \"nat\" and \"tan\" are anagrams. The strings \"ate\", \"eat\", and \"tea\" are anagrams.\\n\\nExample 2:\\nInput: strs = [\"\"]\\nOutput: [[\"\"]]\\nExplanation: The only string in strs is an empty string, so we return a list containing a list with an empty string.\\n\\nExample 3:\\nInput: strs = [\"a\"]\\nOutput: [[\"a\"]]\\nExplanation: The only string in strs is \"a\", so we return a list containing a list with \"a\".",
    "Product of Array Except Self": "Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].\\n\\nThe product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.\\n\\nYou must write an algorithm that runs in O(n) time and without using the division operation.\\n\\nExample 1:\\nInput: nums = [1,2,3,4]\\nOutput: [24,12,8,6]\\nExplanation: The product of all elements except nums[0] is 2*3*4=24. The product of all elements except nums[1] is 1*3*4=12. The product of all elements except nums[2] is 1*2*4=8. The product of all elements except nums[3] is 1*2*3=6.\\n\\nExample 2:\\nInput: nums = [-1,1,0,-3,3]\\nOutput: [0,0,9,0,0]\\nExplanation: The product of all elements except nums[2] is (-1)*1*(-3)*3=9. The product of all elements except any other element is 0 because the array contains a 0.\\n\\nExample 3:\\nInput: nums = [0,0]\\nOutput: [0,0]\\nExplanation: The product of all elements except nums[0] is 0. The product of all elements except nums[1] is 0.",
    "Longest Palindromic Substring": "Given a string s, return the longest palindromic substring in s.\\n\\nExample 1:\\nInput: s = \"babad\"\\nOutput: \"bab\"\\nExplanation: \"aba\" is also a valid answer.\\n\\nExample 2:\\nInput: s = \"cbbd\"\\nOutput: \"bb\"\\nExplanation: \"bb\" is the longest palindromic substring.\\n\\nExample 3:\\nInput: s = \"a\"\\nOutput: \"a\"\\nExplanation: \"a\" is the longest palindromic substring.",
    "Median of Two Sorted Arrays": "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\\n\\nThe overall run time complexity should be O(log (m+n)).\\n\\nExample 1:\\nInput: nums1 = [1,3], nums2 = [2]\\nOutput: 2.00000\\nExplanation: merged array = [1,2,3] and median is 2.\\n\\nExample 2:\\nInput: nums1 = [1,2], nums2 = [3,4]\\nOutput: 2.50000\\nExplanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.\\n\\nExample 3:\\nInput: nums1 = [0,0], nums2 = [0,0]\\nOutput: 0.00000\\nExplanation: merged array = [0,0,0,0] and median is 0.",
    "Merge k Sorted Lists": "You are given an array of k linked-lists lists, each linked-list is sorted in ascending order.\\n\\nMerge all the linked-lists into one sorted linked-list and return it.\\n\\nExample 1:\\nInput: lists = [[1,4,5],[1,3,4],[2,6]]\\nOutput: [1,1,2,3,4,4,5,6]\\nExplanation: merging them into one sorted list: 1->1->2->3->4->4->5->6\\n\\nExample 2:\\nInput: lists = []\\nOutput: []\\nExplanation: There are no lists to merge, so the result is an empty list.\\n\\nExample 3:\\nInput: lists = [[]]\\nOutput: []\\nExplanation: There is one list to merge, but it is empty, so the result is an empty list.",
    "Search in Rotated Sorted Array": "There is an integer array nums sorted in ascending order (with distinct values).\\n\\nPrior to being passed to your function, nums is possibly rotated at an unknown pivot index k (1 <= k < nums.length) such that the resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed).\\n\\nGiven the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.\\n\\nExample 1:\\nInput: nums = [4,5,6,7,0,1,2], target = 0\\nOutput: 4\\nExplanation: The target 0 is found at index 4.\\n\\nExample 2:\\nInput: nums = [4,5,6,7,0,1,2], target = 3\\nOutput: -1\\nExplanation: The target 3 is not found in the array.\\n\\nExample 3:\\nInput: nums = [1], target = 0\\nOutput: -1\\nExplanation: The target 0 is not found in the array.",
    "First Missing Positive": "Given an unsorted integer array nums, return the smallest missing positive integer.\\n\\nYou must implement an algorithm that runs in O(n) time and uses O(1) auxiliary space.\\n\\nExample 1:\\nInput: nums = [1,2,0]\\nOutput: 3\\nExplanation: The numbers in the range [1,2] are all in the array.\\n\\nExample 2:\\nInput: nums = [3,4,-1,1]\\nOutput: 2\\nExplanation: 1 is in the array but 2 is missing.\\n\\nExample 3:\\nInput: nums = [7,8,9,11,12]\\nOutput: 1\\nExplanation: The smallest positive integer 1 is missing.",
    "Permutations": "Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.\\n\\nExample 1:\\nInput: nums = [1,2,3]\\nOutput: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]\\nExplanation: These are all the possible permutations of the array [1,2,3].\\n\\nExample 2:\\nInput: nums = [0,1]\\nOutput: [[0,1],[1,0]]\\nExplanation: These are all the possible permutations of the array [0,1].\\n\\nExample 3:\\nInput: nums = [1]\\nOutput: [[1]]\\nExplanation: There is only one possible permutation of the array [1].",
    "Merge Intervals": "Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.\\n\\nExample 1:\\nInput: intervals = [[1,3],[2,6],[8,10],[15,18]]\\nOutput: [[1,6],[8,10],[15,18]]\\nExplanation: Since intervals [1,3] and [2,6] overlap, merge them into [1,6].\\n\\nExample 2:\\nInput: intervals = [[1,4],[4,5]]\\nOutput: [[1,5]]\\nExplanation: Intervals [1,4] and [4,5] are considered overlapping.\\n\\nExample 3:\\nInput: intervals = [[1,4],[2,3]]\\nOutput: [[1,4]]\\nExplanation: Interval [2,3] is completely contained within interval [1,4].",
    "Jump Game": "You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.\\n\\nReturn true if you can reach the last index, or false otherwise.\\n\\nExample 1:\\nInput: nums = [2,3,1,1,4]\\nOutput: true\\nExplanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.\\n\\nExample 2:\\nInput: nums = [3,2,1,0,4]\\nOutput: false\\nExplanation: You will always arrive at index 3 no matter what. Its maximum jump length is 0, which makes it impossible to reach the last index.\\n\\nExample 3:\\nInput: nums = [0]\\nOutput: true\\nExplanation: You are already at the last index.",
    "Unique Paths": "There is a robot on an m x n grid. The robot is initially located at the top-left corner (i.e., grid[0][0]). The robot tries to move to the bottom-right corner (i.e., grid[m-1][n-1]). The robot can only move either down or right at any point in time.\\n\\nGiven the two integers m and n, return the number of possible unique paths that the robot can take to reach the bottom-right corner.\\n\\nExample 1:\\nInput: m = 3, n = 7\\nOutput: 28\\nExplanation: The robot needs to take a total of 8 steps (2 down, 6 right) to reach the bottom-right corner. The number of unique paths is 28.\\n\\nExample 2:\\nInput: m = 3, n = 2\\nOutput: 3\\nExplanation: From the top-left corner, there are a total of 3 ways to reach the bottom-right corner: 1. Right -> Down -> Down 2. Down -> Down -> Right 3. Down -> Right -> Down\\n\\nExample 3:\\nInput: m = 1, n = 1\\nOutput: 1\\nExplanation: The robot is already at the bottom-right corner.",
    "Edit Distance": "Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.\\n\\nYou have the following three operations permitted on a word: 1. Insert a character 2. Delete a character 3. Replace a character\\n\\nExample 1:\\nInput: word1 = \"horse\", word2 = \"ros\"\\nOutput: 3\\nExplanation: horse -> rorse (replace 'h' with 'r') rorse -> rose (delete 'r') rose -> ros (delete 'e')\\n\\nExample 2:\\nInput: word1 = \"intention\", word2 = \"execution\"\\nOutput: 5\\nExplanation: intention -> inention (remove 't') inention -> enention (replace 'i' with 'e') enention -> exention (replace 'n' with 'x') exention -> exection (replace 'n' with 'c') exection -> execution (insert 'u')\\n\\nExample 3:\\nInput: word1 = \"\", word2 = \"a\"\\nOutput: 1\\nExplanation: Insert 'a' into word1.",
    "Word Search": "Given an m x n grid of characters board and a string word, return true if word exists in the grid.\\n\\nThe word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.\\n\\nExample 1:\\nInput: board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"\\nOutput: true\\nExplanation: The word \"ABCCED\" can be formed by starting at board[0][0] and moving right, down, and left.\\n\\nExample 2:\\nInput: board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"SEE\"\\nOutput: true\\nExplanation: The word \"SEE\" can be formed by starting at board[1][3] and moving left and down.\\n\\nExample 3:\\nInput: board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCB\"\\nOutput: false\\nExplanation: The word \"ABCB\" cannot be formed without reusing the letter 'B' at board[0][1].",
    "Best Time to Buy and Sell Stock": "You are given an array prices where prices[i] is the price of a given stock on the ith day.\\n\\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\\n\\nReturn the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.\\n\\nExample 1:\\nInput: prices = [7,1,5,3,6,4]\\nOutput: 5\\nExplanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5. Note that buying on day 2 and selling on day 1 is not allowed because you must buy before you sell.\\n\\nExample 2:\\nInput: prices = [7,6,4,3,1]\\nOutput: 0\\nExplanation: In this case, no transactions are done and the max profit = 0.\\n\\nExample 3:\\nInput: prices = [1,2]\\nOutput: 1\\nExplanation: Buy on day 1 (price = 1) and sell on day 2 (price = 2), profit = 2-1 = 1.",
    "Linked List Cycle": "Given head, the head of a linked list, determine if the linked list has a cycle in it.\\n\\nThere is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer.\\n\\nReturn true if there is a cycle in the linked list. Otherwise, return false.\\n\\nExample 1:\\nInput: head = [3,2,0,-4], pos = 1\\nOutput: true\\nExplanation: There is a cycle in the linked list, where the tail connects to the 1st node (0-indexed).\\n\\nExample 2:\\nInput: head = [1,2], pos = 0\\nOutput: true\\nExplanation: There is a cycle in the linked list, where the tail connects to the 0th node.\\n\\nExample 3:\\nInput: head = [1], pos = -1\\nOutput: false\\nExplanation: There is no cycle in the linked list.",
    "Longest Consecutive Sequence": "Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.\\n\\nYou must write an algorithm that runs in O(n) time.\\n\\nExample 1:\\nInput: nums = [100,4,200,1,3,2]\\nOutput: 4\\nExplanation: The longest consecutive elements sequence is [1, 2, 3, 4]. Therefore its length is 4.\\n\\nExample 2:\\nInput: nums = [0,3,7,2,5,8,4,6,0,1]\\nOutput: 9\\nExplanation: The longest consecutive elements sequence is [0, 1, 2, 3, 4, 5, 6, 7, 8]. Therefore its length is 9.\\n\\nExample 3:\\nInput: nums = []\\nOutput: 0\\nExplanation: The array is empty, so the longest consecutive elements sequence has length 0."
}

def apply_descriptions():
    with open('scripts/seed_db.py', 'r', encoding='utf-8') as f:
        lines = f.readlines()

    current_title = None
    made_visible = False
    
    for i, line in enumerate(lines):
        title_match = re.search(r'"title":\s*"(.*?)"', line)
        if title_match:
            current_title = title_match.group(1)
            made_visible = False
            continue
            
        desc_match = re.search(r'"description":\s*"(.*?)",\n', line)
        if desc_match and current_title in DESCRIPTIONS:
            new_desc = DESCRIPTIONS[current_title].replace('"', '\\"')
            # Replace the old description with the new one
            lines[i] = re.sub(r'"description":\s*".*",\n', lambda m: f'"description": "{new_desc}",\n', line)
            print(f"Updated description for {current_title}")
            continue
            
        if '"hidden": True' in line and not made_visible:
            # We also need to add more examples if they weren't added. 
            # I am making one hidden testcase visible so the "Example 3" has a corresponding visible testcase!
            # Let's just make the FIRST hidden testcase visible for all problems.
            lines[i] = line.replace('"hidden": True', '"hidden": False')
            made_visible = True

    with open('scripts/seed_db.py', 'w', encoding='utf-8') as f:
        f.writelines(lines)
    print("Done!")

if __name__ == '__main__':
    apply_descriptions()
